- name: play dockercoins
  hosts: control-plane
  gather_facts: no
  tasks:
    - name: Copy dockercoins.yaml on master
      copy: src=k8s-dockercoins.yaml dest=/tmp owner=ubuntu group=ubuntu mode=0644
    - name: Sleep 30 sec
      command: sleep 30
    - name: Deploy dockercoins
      command: kubectl apply -f /tmp/k8s-dockercoins.yaml
    - name: forward input from TCP/8000 to TCP/80 webui service
      command: kubectl port-forward --address 0.0.0.0 --namespace=dockercoins service/webui 8000:80

